title: "Walidad Knowledge Base"
email: "you@walidad.com"
description: "Practical guides and explanations about tax and IRS topics."
baseurl: "" # set to "" when using root domain
url: "https://walidad.com"


theme: minima


enabled_plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap


collections:
articles:
output: true
permalink: /:collection/:path/


markdown: kramdown
kramdown:
input: GFM


# Exclude files from the published site
exclude:
- README.md
- Gemfile
- Gemfile.lock


# Defaults for articles
defaults:
- scope:
path: ""
type: "articles"
values:
layout: "post"
author: "Walidad Ali"


plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
