# ================================
# Site settings
# ================================
title: "Walidad Ali"
description: "Practical guides and explanations about tax and IRS topics."
url: "https://www.walidad.com"
baseurl: ""
locale: "en-US"
timezone: "America/Los_Angeles" # Set for San Francisco

# ================================
# Theme
# ================================
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: air

# ================================
# Plugins
# ================================
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag

# ================================
# Search Settings
# ================================
search: true
search_full_content: true
search_provider: lunr

# ================================
# Collections
# ================================
collections:
  knowledge_base:
    output: true
    permalink: /knowledge-base/:path/
  case_studies:
    output: true
    permalink: /case-studies/:path/

# ================================
# Defaults
# ================================
defaults:
  # 1. THE BASELINE (Pages: Home, Consultation, About)
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: false 
      share: false          
      read_time: false
      classes: "wide"

# 2. THE KNOWLEDGE BASE (Collection)
  - scope:
      path: ""
      type: "knowledge_base"
    values:
      share: true           
      author_profile: false
      
# 3. THE CASE STUDIES (Collection)
  - scope:
      path: ""
      type: "case_studies"
    values:
      share: true           
      author_profile: false
# ================================
# Build Settings
# ================================
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
